### PR TITLE
Added l0 submission , mahipeddu

### PR DESCRIPTION
**Pull request by mahipeddu**

### CODE REVIEW

**Comment by mahipeddu** [comment]
Added L0 , L1 and L2. 2nd commit message wrong, supposed to read L1 :)

**Comment by MarkVI2** [comment]
Please separate submissions

**Comment by SuchirRP** [comment]
Hello There,
U've included all the levels in a single pr, so they'll contribute as only a single pr contribution, as opposed to 3.
Im closing this PR, please open 3 seperate prs one for each level.

Otherwise everything looks nice, good job with the shell, and nice wallpaper.

**Comment by SuchirRP** [comment]
@mahipeddu contacted me and is fine with only having one pr,
so merging

**Pull request merged**
